### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by aferlim** [leticiadedeus/learningPython#1]
Vamos combinar de você apresentar o seu projeto a todos?
Estou curioso!!

**Comment by leticiadedeus** [comment]
Claro, mas ainda tô aprendendo a fazer a insterface (pra aplicações
desktop), então vai demorar um pouco kkkkkkkkkk. MAS SIM, quero muito
mostrar.

Em qui, 13 de mai de 2021 22:19, André Lima ***@***.***>
escreveu:
